#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fante
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="APP")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttablaRecomendados(tablaRecomendados instance);
    partial void UpdatetablaRecomendados(tablaRecomendados instance);
    partial void DeletetablaRecomendados(tablaRecomendados instance);
    partial void InserttablaTarjeta(tablaTarjeta instance);
    partial void UpdatetablaTarjeta(tablaTarjeta instance);
    partial void DeletetablaTarjeta(tablaTarjeta instance);
    partial void InserttablaUsuario(tablaUsuario instance);
    partial void UpdatetablaUsuario(tablaUsuario instance);
    partial void DeletetablaUsuario(tablaUsuario instance);
    partial void InserttablaCreditoUsuario(tablaCreditoUsuario instance);
    partial void UpdatetablaCreditoUsuario(tablaCreditoUsuario instance);
    partial void DeletetablaCreditoUsuario(tablaCreditoUsuario instance);
    partial void InserttablaEjercicios(tablaEjercicios instance);
    partial void UpdatetablaEjercicios(tablaEjercicios instance);
    partial void DeletetablaEjercicios(tablaEjercicios instance);
    partial void InserttablaEnunciadoEjercicios(tablaEnunciadoEjercicios instance);
    partial void UpdatetablaEnunciadoEjercicios(tablaEnunciadoEjercicios instance);
    partial void DeletetablaEnunciadoEjercicios(tablaEnunciadoEjercicios instance);
    partial void InserttablaUbicacionRespuesta(tablaUbicacionRespuesta instance);
    partial void UpdatetablaUbicacionRespuesta(tablaUbicacionRespuesta instance);
    partial void DeletetablaUbicacionRespuesta(tablaUbicacionRespuesta instance);
    partial void InserttablaTipoProducto(tablaTipoProducto instance);
    partial void UpdatetablaTipoProducto(tablaTipoProducto instance);
    partial void DeletetablaTipoProducto(tablaTipoProducto instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["APPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tablaValorOfertas> tablaValorOfertas
		{
			get
			{
				return this.GetTable<tablaValorOfertas>();
			}
		}
		
		public System.Data.Linq.Table<tablaRecomendados> tablaRecomendados
		{
			get
			{
				return this.GetTable<tablaRecomendados>();
			}
		}
		
		public System.Data.Linq.Table<tablaTarjeta> tablaTarjeta
		{
			get
			{
				return this.GetTable<tablaTarjeta>();
			}
		}
		
		public System.Data.Linq.Table<tablaUsuario> tablaUsuario
		{
			get
			{
				return this.GetTable<tablaUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tablaCreditoUsuario> tablaCreditoUsuario
		{
			get
			{
				return this.GetTable<tablaCreditoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<vistaRespuestasEjercicios> vistaRespuestasEjercicios
		{
			get
			{
				return this.GetTable<vistaRespuestasEjercicios>();
			}
		}
		
		public System.Data.Linq.Table<vistaRespuestaVideos> vistaRespuestaVideos
		{
			get
			{
				return this.GetTable<vistaRespuestaVideos>();
			}
		}
		
		public System.Data.Linq.Table<tablaEjercicios> tablaEjercicios
		{
			get
			{
				return this.GetTable<tablaEjercicios>();
			}
		}
		
		public System.Data.Linq.Table<tablaEnunciadoEjercicios> tablaEnunciadoEjercicios
		{
			get
			{
				return this.GetTable<tablaEnunciadoEjercicios>();
			}
		}
		
		public System.Data.Linq.Table<tablaUbicacionRespuesta> tablaUbicacionRespuesta
		{
			get
			{
				return this.GetTable<tablaUbicacionRespuesta>();
			}
		}
		
		public System.Data.Linq.Table<tablaTipoProducto> tablaTipoProducto
		{
			get
			{
				return this.GetTable<tablaTipoProducto>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.loguearUsuarioPC")]
		public int loguearUsuarioPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nickUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string contrasenaUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] ref string respuestas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickUsuario, contrasenaUsuario, respuestas);
			respuestas = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.recuperarContrasenaPC")]
		public int recuperarContrasenaPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nickUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] ref string contrasenaUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickUsuario, contrasenaUsuario);
			contrasenaUsuario = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarUsuarioCelular")]
		public int registrarUsuarioCelular([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoPais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numeroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string contrasenaUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> codigoSMS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPais, numeroCelular, contrasenaUsuario, codigoSMS);
			codigoSMS = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarUsuarioFacebookPC")]
		public int registrarUsuarioFacebookPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> id_Facebook, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string nameFacebook, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(40)")] ref string respuestas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Facebook, nameFacebook, respuestas);
			respuestas = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarUsuarioEmailPC")]
		public int registrarUsuarioEmailPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string correoElectronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string claveUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> respuesta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoElectronico, claveUsuario, respuesta);
			respuesta = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarPerfilUsuarioPC")]
		public ISingleResult<mostrarPerfilUsuarioPCResult> mostrarPerfilUsuarioPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario);
			return ((ISingleResult<mostrarPerfilUsuarioPCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.recomendarUsuarioCelular")]
		public int recomendarUsuarioCelular([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoPais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numeroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPais, numeroCelular, id_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarPerfilCelularPC")]
		public int actualizarPerfilCelularPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoPais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numeroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, codigoPais, numeroCelular, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarPerfilCorreoPC")]
		public int actualizarPerfilCorreoPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string correoElectronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, correoElectronico, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarPerfilContrasenaPC")]
		public int actualizarPerfilContrasenaPC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string contrasenaUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, contrasenaUsuario, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.activarUsuarioCelular")]
		public int activarUsuarioCelular([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoPais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numeroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoSMS, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPais, numeroCelular, codigoSMS, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.recomendarUsuarioCelular")]
		public int recomendarUsuarioCelular1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoPais, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> numeroCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoPais, numeroCelular, id_Usuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cargaSOSCelular")]
		public int cargaSOSCelular([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] ref System.Nullable<decimal> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, resultado);
			resultado = ((System.Nullable<decimal>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cargarCreditoTarjetaPagoTotalSOS")]
		public int cargarCreditoTarjetaPagoTotalSOS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTarjeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, codigoTarjeta, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cargarCreditoTarjetaPagoParcialSOS")]
		public int cargarCreditoTarjetaPagoParcialSOS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTarjeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, codigoTarjeta, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.avisoPrestamoPedido")]
		public int avisoPrestamoPedido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarNombre")]
		public int modificarNombre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id_PedidoEjercicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_PedidoEjercicio);
			id_PedidoEjercicio = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarEjercicioEnviado")]
		public int insertarEjercicioEnviado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string archivoAdjunto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> explicarEjercicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> okRealizado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), archivoAdjunto, explicarEjercicio, okRealizado, id_Usuario, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ubicarRespuestasEjercicios")]
		public ISingleResult<ubicarRespuestasEjerciciosResult> ubicarRespuestasEjercicios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Respuesta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Respuesta);
			return ((ISingleResult<ubicarRespuestasEjerciciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ubicarRespuestasVideos")]
		public ISingleResult<ubicarRespuestasVideosResult> ubicarRespuestasVideos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Respuesta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Respuesta);
			return ((ISingleResult<ubicarRespuestasVideosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.contarRespuestasEjercicios")]
		public int contarRespuestasEjercicios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.contarRespuestasVideos")]
		public int contarRespuestasVideos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarRespuestasEjercicios")]
		public ISingleResult<mostrarRespuestasEjerciciosResult> mostrarRespuestasEjercicios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario);
			return ((ISingleResult<mostrarRespuestasEjerciciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarRespuestasVideos")]
		public ISingleResult<mostrarRespuestasVideosResult> mostrarRespuestasVideos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Usuario);
			return ((ISingleResult<mostrarRespuestasVideosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaValorOfertas")]
	public partial class tablaValorOfertas
	{
		
		private System.Nullable<int> _id_Oferta;
		
		private System.Nullable<bool> _validezOferta;
		
		private System.Nullable<decimal> _valorOferta;
		
		private string _nombreOferta;
		
		public tablaValorOfertas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Oferta", DbType="Int")]
		public System.Nullable<int> id_Oferta
		{
			get
			{
				return this._id_Oferta;
			}
			set
			{
				if ((this._id_Oferta != value))
				{
					this._id_Oferta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validezOferta", DbType="Bit")]
		public System.Nullable<bool> validezOferta
		{
			get
			{
				return this._validezOferta;
			}
			set
			{
				if ((this._validezOferta != value))
				{
					this._validezOferta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorOferta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valorOferta
		{
			get
			{
				return this._valorOferta;
			}
			set
			{
				if ((this._valorOferta != value))
				{
					this._valorOferta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreOferta", DbType="NChar(30)")]
		public string nombreOferta
		{
			get
			{
				return this._nombreOferta;
			}
			set
			{
				if ((this._nombreOferta != value))
				{
					this._nombreOferta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaRecomendados")]
	public partial class tablaRecomendados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_UsuarioRecomendado;
		
		private System.Nullable<int> _codigoPais;
		
		private System.Nullable<long> _numeroCelular;
		
		private System.Nullable<System.DateTime> _fechaRegistro;
		
		private System.Nullable<int> _id_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioRecomendadoChanging(int value);
    partial void Onid_UsuarioRecomendadoChanged();
    partial void OncodigoPaisChanging(System.Nullable<int> value);
    partial void OncodigoPaisChanged();
    partial void OnnumeroCelularChanging(System.Nullable<long> value);
    partial void OnnumeroCelularChanged();
    partial void OnfechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaRegistroChanged();
    partial void Onid_UsuarioChanging(System.Nullable<int> value);
    partial void Onid_UsuarioChanged();
    #endregion
		
		public tablaRecomendados()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_UsuarioRecomendado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_UsuarioRecomendado
		{
			get
			{
				return this._id_UsuarioRecomendado;
			}
			set
			{
				if ((this._id_UsuarioRecomendado != value))
				{
					this.Onid_UsuarioRecomendadoChanging(value);
					this.SendPropertyChanging();
					this._id_UsuarioRecomendado = value;
					this.SendPropertyChanged("id_UsuarioRecomendado");
					this.Onid_UsuarioRecomendadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoPais", DbType="Int")]
		public System.Nullable<int> codigoPais
		{
			get
			{
				return this._codigoPais;
			}
			set
			{
				if ((this._codigoPais != value))
				{
					this.OncodigoPaisChanging(value);
					this.SendPropertyChanging();
					this._codigoPais = value;
					this.SendPropertyChanged("codigoPais");
					this.OncodigoPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCelular", DbType="BigInt")]
		public System.Nullable<long> numeroCelular
		{
			get
			{
				return this._numeroCelular;
			}
			set
			{
				if ((this._numeroCelular != value))
				{
					this.OnnumeroCelularChanging(value);
					this.SendPropertyChanging();
					this._numeroCelular = value;
					this.SendPropertyChanged("numeroCelular");
					this.OnnumeroCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int")]
		public System.Nullable<int> id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this.Onid_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_Usuario = value;
					this.SendPropertyChanged("id_Usuario");
					this.Onid_UsuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaTarjeta")]
	public partial class tablaTarjeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Tarjeta;
		
		private int _codigoTarjeta;
		
		private decimal _creditoTarjeta;
		
		private System.DateTime _vencimientoTarjeta;
		
		private bool _activacionTarjeta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_TarjetaChanging(int value);
    partial void Onid_TarjetaChanged();
    partial void OncodigoTarjetaChanging(int value);
    partial void OncodigoTarjetaChanged();
    partial void OncreditoTarjetaChanging(decimal value);
    partial void OncreditoTarjetaChanged();
    partial void OnvencimientoTarjetaChanging(System.DateTime value);
    partial void OnvencimientoTarjetaChanged();
    partial void OnactivacionTarjetaChanging(bool value);
    partial void OnactivacionTarjetaChanged();
    #endregion
		
		public tablaTarjeta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Tarjeta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Tarjeta
		{
			get
			{
				return this._id_Tarjeta;
			}
			set
			{
				if ((this._id_Tarjeta != value))
				{
					this.Onid_TarjetaChanging(value);
					this.SendPropertyChanging();
					this._id_Tarjeta = value;
					this.SendPropertyChanged("id_Tarjeta");
					this.Onid_TarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoTarjeta", DbType="Int NOT NULL")]
		public int codigoTarjeta
		{
			get
			{
				return this._codigoTarjeta;
			}
			set
			{
				if ((this._codigoTarjeta != value))
				{
					this.OncodigoTarjetaChanging(value);
					this.SendPropertyChanging();
					this._codigoTarjeta = value;
					this.SendPropertyChanged("codigoTarjeta");
					this.OncodigoTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creditoTarjeta", DbType="Decimal(18,2) NOT NULL")]
		public decimal creditoTarjeta
		{
			get
			{
				return this._creditoTarjeta;
			}
			set
			{
				if ((this._creditoTarjeta != value))
				{
					this.OncreditoTarjetaChanging(value);
					this.SendPropertyChanging();
					this._creditoTarjeta = value;
					this.SendPropertyChanged("creditoTarjeta");
					this.OncreditoTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimientoTarjeta", DbType="DateTime NOT NULL")]
		public System.DateTime vencimientoTarjeta
		{
			get
			{
				return this._vencimientoTarjeta;
			}
			set
			{
				if ((this._vencimientoTarjeta != value))
				{
					this.OnvencimientoTarjetaChanging(value);
					this.SendPropertyChanging();
					this._vencimientoTarjeta = value;
					this.SendPropertyChanged("vencimientoTarjeta");
					this.OnvencimientoTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activacionTarjeta", DbType="Bit NOT NULL")]
		public bool activacionTarjeta
		{
			get
			{
				return this._activacionTarjeta;
			}
			set
			{
				if ((this._activacionTarjeta != value))
				{
					this.OnactivacionTarjetaChanging(value);
					this.SendPropertyChanging();
					this._activacionTarjeta = value;
					this.SendPropertyChanged("activacionTarjeta");
					this.OnactivacionTarjetaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaUsuario")]
	public partial class tablaUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Usuario;
		
		private int _codigoPais;
		
		private long _numeroCelular;
		
		private string _contrasenaUsuario;
		
		private bool _activacionUsuario;
		
		private System.Nullable<int> _codigoSMS;
		
		private string _correoElectronico;
		
		private System.Nullable<int> _id_Facebook;
		
		private string _nameFacebook;
		
		private EntityRef<tablaCreditoUsuario> _tablaCreditoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void OncodigoPaisChanging(int value);
    partial void OncodigoPaisChanged();
    partial void OnnumeroCelularChanging(long value);
    partial void OnnumeroCelularChanged();
    partial void OncontrasenaUsuarioChanging(string value);
    partial void OncontrasenaUsuarioChanged();
    partial void OnactivacionUsuarioChanging(bool value);
    partial void OnactivacionUsuarioChanged();
    partial void OncodigoSMSChanging(System.Nullable<int> value);
    partial void OncodigoSMSChanged();
    partial void OncorreoElectronicoChanging(string value);
    partial void OncorreoElectronicoChanged();
    partial void Onid_FacebookChanging(System.Nullable<int> value);
    partial void Onid_FacebookChanged();
    partial void OnnameFacebookChanging(string value);
    partial void OnnameFacebookChanged();
    #endregion
		
		public tablaUsuario()
		{
			this._tablaCreditoUsuario = default(EntityRef<tablaCreditoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this.Onid_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_Usuario = value;
					this.SendPropertyChanged("id_Usuario");
					this.Onid_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoPais", DbType="Int NOT NULL")]
		public int codigoPais
		{
			get
			{
				return this._codigoPais;
			}
			set
			{
				if ((this._codigoPais != value))
				{
					this.OncodigoPaisChanging(value);
					this.SendPropertyChanging();
					this._codigoPais = value;
					this.SendPropertyChanged("codigoPais");
					this.OncodigoPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCelular", DbType="BigInt NOT NULL")]
		public long numeroCelular
		{
			get
			{
				return this._numeroCelular;
			}
			set
			{
				if ((this._numeroCelular != value))
				{
					this.OnnumeroCelularChanging(value);
					this.SendPropertyChanging();
					this._numeroCelular = value;
					this.SendPropertyChanged("numeroCelular");
					this.OnnumeroCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenaUsuario", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string contrasenaUsuario
		{
			get
			{
				return this._contrasenaUsuario;
			}
			set
			{
				if ((this._contrasenaUsuario != value))
				{
					this.OncontrasenaUsuarioChanging(value);
					this.SendPropertyChanging();
					this._contrasenaUsuario = value;
					this.SendPropertyChanged("contrasenaUsuario");
					this.OncontrasenaUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activacionUsuario", DbType="Bit NOT NULL")]
		public bool activacionUsuario
		{
			get
			{
				return this._activacionUsuario;
			}
			set
			{
				if ((this._activacionUsuario != value))
				{
					this.OnactivacionUsuarioChanging(value);
					this.SendPropertyChanging();
					this._activacionUsuario = value;
					this.SendPropertyChanged("activacionUsuario");
					this.OnactivacionUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoSMS", DbType="Int")]
		public System.Nullable<int> codigoSMS
		{
			get
			{
				return this._codigoSMS;
			}
			set
			{
				if ((this._codigoSMS != value))
				{
					this.OncodigoSMSChanging(value);
					this.SendPropertyChanging();
					this._codigoSMS = value;
					this.SendPropertyChanged("codigoSMS");
					this.OncodigoSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="NVarChar(30)")]
		public string correoElectronico
		{
			get
			{
				return this._correoElectronico;
			}
			set
			{
				if ((this._correoElectronico != value))
				{
					this.OncorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._correoElectronico = value;
					this.SendPropertyChanged("correoElectronico");
					this.OncorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Facebook", DbType="Int")]
		public System.Nullable<int> id_Facebook
		{
			get
			{
				return this._id_Facebook;
			}
			set
			{
				if ((this._id_Facebook != value))
				{
					this.Onid_FacebookChanging(value);
					this.SendPropertyChanging();
					this._id_Facebook = value;
					this.SendPropertyChanged("id_Facebook");
					this.Onid_FacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameFacebook", DbType="NVarChar(30)")]
		public string nameFacebook
		{
			get
			{
				return this._nameFacebook;
			}
			set
			{
				if ((this._nameFacebook != value))
				{
					this.OnnameFacebookChanging(value);
					this.SendPropertyChanging();
					this._nameFacebook = value;
					this.SendPropertyChanged("nameFacebook");
					this.OnnameFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaUsuario_tablaCreditoUsuario", Storage="_tablaCreditoUsuario", ThisKey="id_Usuario", OtherKey="id_Usuario", IsUnique=true, IsForeignKey=false)]
		public tablaCreditoUsuario tablaCreditoUsuario
		{
			get
			{
				return this._tablaCreditoUsuario.Entity;
			}
			set
			{
				tablaCreditoUsuario previousValue = this._tablaCreditoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tablaCreditoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaCreditoUsuario.Entity = null;
						previousValue.tablaUsuario = null;
					}
					this._tablaCreditoUsuario.Entity = value;
					if ((value != null))
					{
						value.tablaUsuario = this;
					}
					this.SendPropertyChanged("tablaCreditoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaCreditoUsuario")]
	public partial class tablaCreditoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Usuario;
		
		private decimal _creditoUsuario;
		
		private System.Nullable<decimal> _prestamoReal;
		
		private System.Nullable<bool> _prestamoSOS;
		
		private System.Nullable<int> _bonificacionRecarga;
		
		private EntityRef<tablaUsuario> _tablaUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void OncreditoUsuarioChanging(decimal value);
    partial void OncreditoUsuarioChanged();
    partial void OnprestamoRealChanging(System.Nullable<decimal> value);
    partial void OnprestamoRealChanged();
    partial void OnprestamoSOSChanging(System.Nullable<bool> value);
    partial void OnprestamoSOSChanged();
    partial void OnbonificacionRecargaChanging(System.Nullable<int> value);
    partial void OnbonificacionRecargaChanged();
    #endregion
		
		public tablaCreditoUsuario()
		{
			this._tablaUsuario = default(EntityRef<tablaUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					if (this._tablaUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_Usuario = value;
					this.SendPropertyChanged("id_Usuario");
					this.Onid_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creditoUsuario", DbType="Decimal(18,2) NOT NULL")]
		public decimal creditoUsuario
		{
			get
			{
				return this._creditoUsuario;
			}
			set
			{
				if ((this._creditoUsuario != value))
				{
					this.OncreditoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._creditoUsuario = value;
					this.SendPropertyChanged("creditoUsuario");
					this.OncreditoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prestamoReal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> prestamoReal
		{
			get
			{
				return this._prestamoReal;
			}
			set
			{
				if ((this._prestamoReal != value))
				{
					this.OnprestamoRealChanging(value);
					this.SendPropertyChanging();
					this._prestamoReal = value;
					this.SendPropertyChanged("prestamoReal");
					this.OnprestamoRealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prestamoSOS", DbType="Bit")]
		public System.Nullable<bool> prestamoSOS
		{
			get
			{
				return this._prestamoSOS;
			}
			set
			{
				if ((this._prestamoSOS != value))
				{
					this.OnprestamoSOSChanging(value);
					this.SendPropertyChanging();
					this._prestamoSOS = value;
					this.SendPropertyChanged("prestamoSOS");
					this.OnprestamoSOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bonificacionRecarga", DbType="Int")]
		public System.Nullable<int> bonificacionRecarga
		{
			get
			{
				return this._bonificacionRecarga;
			}
			set
			{
				if ((this._bonificacionRecarga != value))
				{
					this.OnbonificacionRecargaChanging(value);
					this.SendPropertyChanging();
					this._bonificacionRecarga = value;
					this.SendPropertyChanged("bonificacionRecarga");
					this.OnbonificacionRecargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaUsuario_tablaCreditoUsuario", Storage="_tablaUsuario", ThisKey="id_Usuario", OtherKey="id_Usuario", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tablaUsuario tablaUsuario
		{
			get
			{
				return this._tablaUsuario.Entity;
			}
			set
			{
				tablaUsuario previousValue = this._tablaUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tablaUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaUsuario.Entity = null;
						previousValue.tablaCreditoUsuario = null;
					}
					this._tablaUsuario.Entity = value;
					if ((value != null))
					{
						value.tablaCreditoUsuario = this;
						this._id_Usuario = value.id_Usuario;
					}
					else
					{
						this._id_Usuario = default(int);
					}
					this.SendPropertyChanged("tablaUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaRespuestasEjercicios")]
	public partial class vistaRespuestasEjercicios
	{
		
		private int _id_Ejercicio;
		
		private System.DateTime _vencimientoEjercicio;
		
		private int _id_Usuario;
		
		private string _tituloEjercicio;
		
		private string _ubicacionRespuestaEjercicio;
		
		private int _id_Respuesta;
		
		public vistaRespuestasEjercicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL")]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					this._id_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimientoEjercicio", DbType="DateTime NOT NULL")]
		public System.DateTime vencimientoEjercicio
		{
			get
			{
				return this._vencimientoEjercicio;
			}
			set
			{
				if ((this._vencimientoEjercicio != value))
				{
					this._vencimientoEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL")]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this._id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEjercicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tituloEjercicio
		{
			get
			{
				return this._tituloEjercicio;
			}
			set
			{
				if ((this._tituloEjercicio != value))
				{
					this._tituloEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionRespuestaEjercicio", DbType="NVarChar(40)")]
		public string ubicacionRespuestaEjercicio
		{
			get
			{
				return this._ubicacionRespuestaEjercicio;
			}
			set
			{
				if ((this._ubicacionRespuestaEjercicio != value))
				{
					this._ubicacionRespuestaEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Respuesta", DbType="Int NOT NULL")]
		public int id_Respuesta
		{
			get
			{
				return this._id_Respuesta;
			}
			set
			{
				if ((this._id_Respuesta != value))
				{
					this._id_Respuesta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaRespuestaVideos")]
	public partial class vistaRespuestaVideos
	{
		
		private int _id_Ejercicio;
		
		private string _ubicacionVideosExplicaciones;
		
		private int _id_Usuario;
		
		private System.DateTime _vencimientoEjercicio;
		
		private string _tituloEjercicio;
		
		private int _id_Respuesta;
		
		public vistaRespuestaVideos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL")]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					this._id_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionVideosExplicaciones", DbType="NVarChar(100)")]
		public string ubicacionVideosExplicaciones
		{
			get
			{
				return this._ubicacionVideosExplicaciones;
			}
			set
			{
				if ((this._ubicacionVideosExplicaciones != value))
				{
					this._ubicacionVideosExplicaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL")]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this._id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimientoEjercicio", DbType="DateTime NOT NULL")]
		public System.DateTime vencimientoEjercicio
		{
			get
			{
				return this._vencimientoEjercicio;
			}
			set
			{
				if ((this._vencimientoEjercicio != value))
				{
					this._vencimientoEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEjercicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tituloEjercicio
		{
			get
			{
				return this._tituloEjercicio;
			}
			set
			{
				if ((this._tituloEjercicio != value))
				{
					this._tituloEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Respuesta", DbType="Int NOT NULL")]
		public int id_Respuesta
		{
			get
			{
				return this._id_Respuesta;
			}
			set
			{
				if ((this._id_Respuesta != value))
				{
					this._id_Respuesta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaEjercicios")]
	public partial class tablaEjercicios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Ejercicio;
		
		private System.Nullable<int> _id_TipoEjercicio;
		
		private System.Nullable<bool> _explicacionRealizada;
		
		private EntityRef<tablaEnunciadoEjercicios> _tablaEnunciadoEjercicios;
		
		private EntityRef<tablaTipoProducto> _tablaTipoProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_EjercicioChanging(int value);
    partial void Onid_EjercicioChanged();
    partial void Onid_TipoEjercicioChanging(System.Nullable<int> value);
    partial void Onid_TipoEjercicioChanged();
    partial void OnexplicacionRealizadaChanging(System.Nullable<bool> value);
    partial void OnexplicacionRealizadaChanged();
    #endregion
		
		public tablaEjercicios()
		{
			this._tablaEnunciadoEjercicios = default(EntityRef<tablaEnunciadoEjercicios>);
			this._tablaTipoProducto = default(EntityRef<tablaTipoProducto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					if (this._tablaEnunciadoEjercicios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._id_Ejercicio = value;
					this.SendPropertyChanged("id_Ejercicio");
					this.Onid_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_TipoEjercicio", DbType="Int")]
		public System.Nullable<int> id_TipoEjercicio
		{
			get
			{
				return this._id_TipoEjercicio;
			}
			set
			{
				if ((this._id_TipoEjercicio != value))
				{
					if (this._tablaTipoProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_TipoEjercicioChanging(value);
					this.SendPropertyChanging();
					this._id_TipoEjercicio = value;
					this.SendPropertyChanged("id_TipoEjercicio");
					this.Onid_TipoEjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_explicacionRealizada", DbType="Bit")]
		public System.Nullable<bool> explicacionRealizada
		{
			get
			{
				return this._explicacionRealizada;
			}
			set
			{
				if ((this._explicacionRealizada != value))
				{
					this.OnexplicacionRealizadaChanging(value);
					this.SendPropertyChanging();
					this._explicacionRealizada = value;
					this.SendPropertyChanged("explicacionRealizada");
					this.OnexplicacionRealizadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaEnunciadoEjercicios_tablaEjercicios", Storage="_tablaEnunciadoEjercicios", ThisKey="id_Ejercicio", OtherKey="id_Ejercicio", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tablaEnunciadoEjercicios tablaEnunciadoEjercicios
		{
			get
			{
				return this._tablaEnunciadoEjercicios.Entity;
			}
			set
			{
				tablaEnunciadoEjercicios previousValue = this._tablaEnunciadoEjercicios.Entity;
				if (((previousValue != value) 
							|| (this._tablaEnunciadoEjercicios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaEnunciadoEjercicios.Entity = null;
						previousValue.tablaEjercicios = null;
					}
					this._tablaEnunciadoEjercicios.Entity = value;
					if ((value != null))
					{
						value.tablaEjercicios = this;
						this._id_Ejercicio = value.id_Ejercicio;
					}
					else
					{
						this._id_Ejercicio = default(int);
					}
					this.SendPropertyChanged("tablaEnunciadoEjercicios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaTipoProducto_tablaEjercicios", Storage="_tablaTipoProducto", ThisKey="id_TipoEjercicio", OtherKey="id_TipoEjercicio", IsForeignKey=true, DeleteRule="CASCADE")]
		public tablaTipoProducto tablaTipoProducto
		{
			get
			{
				return this._tablaTipoProducto.Entity;
			}
			set
			{
				tablaTipoProducto previousValue = this._tablaTipoProducto.Entity;
				if (((previousValue != value) 
							|| (this._tablaTipoProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaTipoProducto.Entity = null;
						previousValue.tablaEjercicios.Remove(this);
					}
					this._tablaTipoProducto.Entity = value;
					if ((value != null))
					{
						value.tablaEjercicios.Add(this);
						this._id_TipoEjercicio = value.id_TipoEjercicio;
					}
					else
					{
						this._id_TipoEjercicio = default(Nullable<int>);
					}
					this.SendPropertyChanged("tablaTipoProducto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaEnunciadoEjercicios")]
	public partial class tablaEnunciadoEjercicios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Ejercicio;
		
		private string _enunciadoMATH;
		
		private string _enunciadoLimpio;
		
		private EntityRef<tablaEjercicios> _tablaEjercicios;
		
		private EntityRef<tablaUbicacionRespuesta> _tablaUbicacionRespuesta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_EjercicioChanging(int value);
    partial void Onid_EjercicioChanged();
    partial void OnenunciadoMATHChanging(string value);
    partial void OnenunciadoMATHChanged();
    partial void OnenunciadoLimpioChanging(string value);
    partial void OnenunciadoLimpioChanged();
    #endregion
		
		public tablaEnunciadoEjercicios()
		{
			this._tablaEjercicios = default(EntityRef<tablaEjercicios>);
			this._tablaUbicacionRespuesta = default(EntityRef<tablaUbicacionRespuesta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					this.Onid_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._id_Ejercicio = value;
					this.SendPropertyChanged("id_Ejercicio");
					this.Onid_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enunciadoMATH", DbType="NVarChar(MAX)")]
		public string enunciadoMATH
		{
			get
			{
				return this._enunciadoMATH;
			}
			set
			{
				if ((this._enunciadoMATH != value))
				{
					this.OnenunciadoMATHChanging(value);
					this.SendPropertyChanging();
					this._enunciadoMATH = value;
					this.SendPropertyChanged("enunciadoMATH");
					this.OnenunciadoMATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enunciadoLimpio", DbType="NVarChar(MAX)")]
		public string enunciadoLimpio
		{
			get
			{
				return this._enunciadoLimpio;
			}
			set
			{
				if ((this._enunciadoLimpio != value))
				{
					this.OnenunciadoLimpioChanging(value);
					this.SendPropertyChanging();
					this._enunciadoLimpio = value;
					this.SendPropertyChanged("enunciadoLimpio");
					this.OnenunciadoLimpioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaEnunciadoEjercicios_tablaEjercicios", Storage="_tablaEjercicios", ThisKey="id_Ejercicio", OtherKey="id_Ejercicio", IsUnique=true, IsForeignKey=false)]
		public tablaEjercicios tablaEjercicios
		{
			get
			{
				return this._tablaEjercicios.Entity;
			}
			set
			{
				tablaEjercicios previousValue = this._tablaEjercicios.Entity;
				if (((previousValue != value) 
							|| (this._tablaEjercicios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaEjercicios.Entity = null;
						previousValue.tablaEnunciadoEjercicios = null;
					}
					this._tablaEjercicios.Entity = value;
					if ((value != null))
					{
						value.tablaEnunciadoEjercicios = this;
					}
					this.SendPropertyChanged("tablaEjercicios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaEnunciadoEjercicios_tablaUbicacionRespuesta", Storage="_tablaUbicacionRespuesta", ThisKey="id_Ejercicio", OtherKey="id_Ejercicio", IsUnique=true, IsForeignKey=false)]
		public tablaUbicacionRespuesta tablaUbicacionRespuesta
		{
			get
			{
				return this._tablaUbicacionRespuesta.Entity;
			}
			set
			{
				tablaUbicacionRespuesta previousValue = this._tablaUbicacionRespuesta.Entity;
				if (((previousValue != value) 
							|| (this._tablaUbicacionRespuesta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaUbicacionRespuesta.Entity = null;
						previousValue.tablaEnunciadoEjercicios = null;
					}
					this._tablaUbicacionRespuesta.Entity = value;
					if ((value != null))
					{
						value.tablaEnunciadoEjercicios = this;
					}
					this.SendPropertyChanged("tablaUbicacionRespuesta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaUbicacionRespuesta")]
	public partial class tablaUbicacionRespuesta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Ejercicio;
		
		private string _ubicacionRespuestaEjercicio;
		
		private string _ubicacionVideosExplicaciones;
		
		private EntityRef<tablaEnunciadoEjercicios> _tablaEnunciadoEjercicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_EjercicioChanging(int value);
    partial void Onid_EjercicioChanged();
    partial void OnubicacionRespuestaEjercicioChanging(string value);
    partial void OnubicacionRespuestaEjercicioChanged();
    partial void OnubicacionVideosExplicacionesChanging(string value);
    partial void OnubicacionVideosExplicacionesChanged();
    #endregion
		
		public tablaUbicacionRespuesta()
		{
			this._tablaEnunciadoEjercicios = default(EntityRef<tablaEnunciadoEjercicios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					if (this._tablaEnunciadoEjercicios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._id_Ejercicio = value;
					this.SendPropertyChanged("id_Ejercicio");
					this.Onid_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionRespuestaEjercicio", DbType="NVarChar(40)")]
		public string ubicacionRespuestaEjercicio
		{
			get
			{
				return this._ubicacionRespuestaEjercicio;
			}
			set
			{
				if ((this._ubicacionRespuestaEjercicio != value))
				{
					this.OnubicacionRespuestaEjercicioChanging(value);
					this.SendPropertyChanging();
					this._ubicacionRespuestaEjercicio = value;
					this.SendPropertyChanged("ubicacionRespuestaEjercicio");
					this.OnubicacionRespuestaEjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionVideosExplicaciones", DbType="NVarChar(100)")]
		public string ubicacionVideosExplicaciones
		{
			get
			{
				return this._ubicacionVideosExplicaciones;
			}
			set
			{
				if ((this._ubicacionVideosExplicaciones != value))
				{
					this.OnubicacionVideosExplicacionesChanging(value);
					this.SendPropertyChanging();
					this._ubicacionVideosExplicaciones = value;
					this.SendPropertyChanged("ubicacionVideosExplicaciones");
					this.OnubicacionVideosExplicacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaEnunciadoEjercicios_tablaUbicacionRespuesta", Storage="_tablaEnunciadoEjercicios", ThisKey="id_Ejercicio", OtherKey="id_Ejercicio", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tablaEnunciadoEjercicios tablaEnunciadoEjercicios
		{
			get
			{
				return this._tablaEnunciadoEjercicios.Entity;
			}
			set
			{
				tablaEnunciadoEjercicios previousValue = this._tablaEnunciadoEjercicios.Entity;
				if (((previousValue != value) 
							|| (this._tablaEnunciadoEjercicios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tablaEnunciadoEjercicios.Entity = null;
						previousValue.tablaUbicacionRespuesta = null;
					}
					this._tablaEnunciadoEjercicios.Entity = value;
					if ((value != null))
					{
						value.tablaUbicacionRespuesta = this;
						this._id_Ejercicio = value.id_Ejercicio;
					}
					else
					{
						this._id_Ejercicio = default(int);
					}
					this.SendPropertyChanged("tablaEnunciadoEjercicios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablaTipoProducto")]
	public partial class tablaTipoProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_TipoEjercicio;
		
		private string _tipoProducto;
		
		private EntitySet<tablaEjercicios> _tablaEjercicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_TipoEjercicioChanging(int value);
    partial void Onid_TipoEjercicioChanged();
    partial void OntipoProductoChanging(string value);
    partial void OntipoProductoChanged();
    #endregion
		
		public tablaTipoProducto()
		{
			this._tablaEjercicios = new EntitySet<tablaEjercicios>(new Action<tablaEjercicios>(this.attach_tablaEjercicios), new Action<tablaEjercicios>(this.detach_tablaEjercicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_TipoEjercicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_TipoEjercicio
		{
			get
			{
				return this._id_TipoEjercicio;
			}
			set
			{
				if ((this._id_TipoEjercicio != value))
				{
					this.Onid_TipoEjercicioChanging(value);
					this.SendPropertyChanging();
					this._id_TipoEjercicio = value;
					this.SendPropertyChanged("id_TipoEjercicio");
					this.Onid_TipoEjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoProducto", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tipoProducto
		{
			get
			{
				return this._tipoProducto;
			}
			set
			{
				if ((this._tipoProducto != value))
				{
					this.OntipoProductoChanging(value);
					this.SendPropertyChanging();
					this._tipoProducto = value;
					this.SendPropertyChanged("tipoProducto");
					this.OntipoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tablaTipoProducto_tablaEjercicios", Storage="_tablaEjercicios", ThisKey="id_TipoEjercicio", OtherKey="id_TipoEjercicio")]
		public EntitySet<tablaEjercicios> tablaEjercicios
		{
			get
			{
				return this._tablaEjercicios;
			}
			set
			{
				this._tablaEjercicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tablaEjercicios(tablaEjercicios entity)
		{
			this.SendPropertyChanging();
			entity.tablaTipoProducto = this;
		}
		
		private void detach_tablaEjercicios(tablaEjercicios entity)
		{
			this.SendPropertyChanging();
			entity.tablaTipoProducto = null;
		}
	}
	
	public partial class mostrarPerfilUsuarioPCResult
	{
		
		private string _correoElectronico;
		
		private string _contrasenaUsuario;
		
		private System.Nullable<long> _numeroCelular;
		
		private System.Nullable<int> _codigoPais;
		
		public mostrarPerfilUsuarioPCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="NVarChar(30)")]
		public string correoElectronico
		{
			get
			{
				return this._correoElectronico;
			}
			set
			{
				if ((this._correoElectronico != value))
				{
					this._correoElectronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenaUsuario", DbType="NVarChar(10)")]
		public string contrasenaUsuario
		{
			get
			{
				return this._contrasenaUsuario;
			}
			set
			{
				if ((this._contrasenaUsuario != value))
				{
					this._contrasenaUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCelular", DbType="BigInt")]
		public System.Nullable<long> numeroCelular
		{
			get
			{
				return this._numeroCelular;
			}
			set
			{
				if ((this._numeroCelular != value))
				{
					this._numeroCelular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoPais", DbType="Int")]
		public System.Nullable<int> codigoPais
		{
			get
			{
				return this._codigoPais;
			}
			set
			{
				if ((this._codigoPais != value))
				{
					this._codigoPais = value;
				}
			}
		}
	}
	
	public partial class ubicarRespuestasEjerciciosResult
	{
		
		private string _ubicacionRespuestaEjercicio;
		
		public ubicarRespuestasEjerciciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionRespuestaEjercicio", DbType="NVarChar(40)")]
		public string ubicacionRespuestaEjercicio
		{
			get
			{
				return this._ubicacionRespuestaEjercicio;
			}
			set
			{
				if ((this._ubicacionRespuestaEjercicio != value))
				{
					this._ubicacionRespuestaEjercicio = value;
				}
			}
		}
	}
	
	public partial class ubicarRespuestasVideosResult
	{
		
		private string _ubicacionVideosExplicaciones;
		
		public ubicarRespuestasVideosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionVideosExplicaciones", DbType="NVarChar(100)")]
		public string ubicacionVideosExplicaciones
		{
			get
			{
				return this._ubicacionVideosExplicaciones;
			}
			set
			{
				if ((this._ubicacionVideosExplicaciones != value))
				{
					this._ubicacionVideosExplicaciones = value;
				}
			}
		}
	}
	
	public partial class mostrarRespuestasEjerciciosResult
	{
		
		private int _id_Ejercicio;
		
		private System.DateTime _vencimientoEjercicio;
		
		private string _tituloEjercicio;
		
		private int _id_Usuario;
		
		private int _id_Respuesta;
		
		public mostrarRespuestasEjerciciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL")]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					this._id_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimientoEjercicio", DbType="DateTime NOT NULL")]
		public System.DateTime vencimientoEjercicio
		{
			get
			{
				return this._vencimientoEjercicio;
			}
			set
			{
				if ((this._vencimientoEjercicio != value))
				{
					this._vencimientoEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEjercicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tituloEjercicio
		{
			get
			{
				return this._tituloEjercicio;
			}
			set
			{
				if ((this._tituloEjercicio != value))
				{
					this._tituloEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL")]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this._id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Respuesta", DbType="Int NOT NULL")]
		public int id_Respuesta
		{
			get
			{
				return this._id_Respuesta;
			}
			set
			{
				if ((this._id_Respuesta != value))
				{
					this._id_Respuesta = value;
				}
			}
		}
	}
	
	public partial class mostrarRespuestasVideosResult
	{
		
		private int _id_Ejercicio;
		
		private System.DateTime _vencimientoEjercicio;
		
		private string _tituloEjercicio;
		
		private int _id_Usuario;
		
		private int _id_Respuesta;
		
		public mostrarRespuestasVideosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Ejercicio", DbType="Int NOT NULL")]
		public int id_Ejercicio
		{
			get
			{
				return this._id_Ejercicio;
			}
			set
			{
				if ((this._id_Ejercicio != value))
				{
					this._id_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimientoEjercicio", DbType="DateTime NOT NULL")]
		public System.DateTime vencimientoEjercicio
		{
			get
			{
				return this._vencimientoEjercicio;
			}
			set
			{
				if ((this._vencimientoEjercicio != value))
				{
					this._vencimientoEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tituloEjercicio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tituloEjercicio
		{
			get
			{
				return this._tituloEjercicio;
			}
			set
			{
				if ((this._tituloEjercicio != value))
				{
					this._tituloEjercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int NOT NULL")]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this._id_Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Respuesta", DbType="Int NOT NULL")]
		public int id_Respuesta
		{
			get
			{
				return this._id_Respuesta;
			}
			set
			{
				if ((this._id_Respuesta != value))
				{
					this._id_Respuesta = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
